/**
 * User administration — the Users & Roles screen.
 *
 * Adding somebody is **two facts on separate routes**, and the screen has to
 * say so or the person will never get in:
 *
 *   the password   generated by the server, shown back **once**, never
 *                  emailed. The lead passes it on themselves.
 *   the code       emailed to the person's own address. Until they enter it
 *                  at `/auth/verify-email/`, signing in is refused.
 *
 * Keeping them on separate routes is what makes the code worth anything —
 * both in one inbox would prove nothing. So the create screen must show the
 * password immediately and warn that it cannot be shown again.
 *
 * Roles cannot be created. There are five, fixed in code, because each maps
 * to a column of AsOne's access matrix. `roles()` in `auth.ts` lists them for
 * the dropdown; this module assigns one to a person.
 */

import { get, patch, post } from './http'
import type { Page, UserAdmin, UserCreate } from './types'

/** A newly created account: the record, and the password shown once. */
export interface CreatedUser {
  user: UserAdmin
  /** Null when the lead typed their own. Show it, then it is gone forever. */
  password: string | null
  detail: string
}

/**
 * The staff list, paged.
 *
 * `page_size` is sent, not left to the server. DRF's default is fifty, so
 * without it the client's page size was a number it computed with and the
 * server ignored: the footer said "Showing 1-15 of 12" and the page controls
 * never appeared, because everything had come back on one page.
 */
export function list(params?: {
  role?: string
  is_active?: boolean
  search?: string
  page?: number
  page_size?: number
}) {
  return get<Page<UserAdmin>>('/auth/users/', params ?? undefined)
}

export function retrieve(id: number) {
  return get<UserAdmin>(`/auth/users/${id}/`)
}

/**
 * Add a member of staff.
 *
 * Omit `password` — the server generates one and returns it once. Warehouse
 * staff need a `warehouse`, school staff a `school`, and the three
 * all-locations roles take neither; sending the wrong one is a 400.
 *
 * A 503 means the confirmation email could not be sent and **nothing was
 * saved** — the account does not exist and the lead can simply try again.
 * Treat it as retryable, not as a failure to report.
 */
export function create(body: UserCreate) {
  return post<CreatedUser>('/auth/users/', body)
}

/** Edit name, email, role or site. Not the password — that has its own route. */
export function update(id: number, body: Partial<UserAdmin>) {
  return patch<UserAdmin>(`/auth/users/${id}/`, body)
}

/**
 * Set somebody else's password, for when they have forgotten it.
 *
 * Returns the new password once. **Signs that account out everywhere**, so
 * warn before submitting rather than after: anyone signed in on another
 * device is dropped.
 */
export function setPassword(id: number, body?: { new_password?: string }) {
  return post<{ password: string; detail: string }>(
    `/auth/users/${id}/set-password/`,
    body ?? {},
  )
}

/**
 * Email a fresh confirmation code and retire the old one.
 *
 * For a code that expired — they last seven days — or an email that went
 * astray. Refused with a 400 once the address is confirmed: there is nothing
 * left to prove, and re-sending would let anybody with lead access quietly
 * reset an account. Use `setPassword` for that; it is visible.
 */
export function resendVerification(id: number) {
  return post<{ detail: string }>(`/auth/users/${id}/resend-verification/`, {})
}

/** Accounts are deactivated, never deleted — past transactions point at them. */
export function deactivate(id: number) {
  return post<UserAdmin>(`/auth/users/${id}/deactivate/`, {})
}

export function activate(id: number) {
  return post<UserAdmin>(`/auth/users/${id}/activate/`, {})
}

/**
 * Drop every one of that account's sessions, without changing the password.
 *
 * Returns how many were retired, which is worth showing: zero means they
 * were not signed in anywhere, and that is a different answer from "done".
 */
export function signOut(id: number) {
  return post<{ sessions_retired: number }>(`/auth/users/${id}/sign-out/`, {})
}
